# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e2848211c5035d954a79a66e66a33404f793c01bcda1d9057380d6da81aae4d9adec4b128dadcb877daae5828842e6bdff1d2bb6bfb66b6726a2fff7147d06

test:
  secret_key_base: 1288674147eb157615640c9afb6a50086c92ef9acdabfcdd68d1def290ac30bd432ad3090c631aeb6e97aac22c01f677851ceb3804df776d1347788870c2e527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
